version: '3'
services:
  backend:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./backend/:/usr/src/app
    command: bash -c "npm install && npm start"
    ports:
      - "1400:1400"
    environment:
        - WEBSOCKET_PORT=1400